name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default
      - name: Build
        run: swift build -v
      - name: Run tests
        run: |
         eval "$(docker-machine env default)"
         swift test --enable-code-coverage --sanitize=thread
      - name: Convert coverage files
        run: |
          xcrun llvm-cov export -format "lcov" \
            .build/debug/AWSDeployKitPackageTests.xctest/Contents/MacOs/AWSDeployKitPackageTests \
            -ignore-filename-regex="\/Tests\/" \
            -instr-profile=.build/debug/codecov/default.profdata > info.lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: info.lcov
