name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_docker:
      runs-on: macos-latest
      steps:
        - name: echo
          run: |
            brew install docker-machine docker
            mkdir -p /Users/runner/.docker/machine/cache/
            curl -o ~/.docker/machine/cache/default https://api.github.com/repos/boot2docker/boot2docker/releases/latest
            docker-machine create default
            eval $(docker-machine env default)
            sudo docker version
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --sanitize=thread
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/AWSDeployKitPackageTests.xctest/Contents/MacOs/AWSDeployKitPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov  
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov
